<<<<<<< HEAD
"""
    BroFar's Happy Bunny Rabbit Pattern Challenge.
    Created on February 21, 2023.
    Made by T0N1.
"""
print()
print()
print()
print('*           *'.center(35))
print('**           **'.center(35))
print('* *          * *'.center(35))
print('*  *        * *'.center(35))
print('*  *      *  *'.center(35))
print('*  *     *  *'.center(35))
print('*  *    *  *'.center(35))
print('* * ** * *'.center(35))
print('**    **'.center(35))
print('*          *'.center(35))
print('*   o   o   *'.center(35))
print('*     _      *'.center(35))
print('*  \\\\. V .//  *'.center(35))
print(',* ._       _.  *,'.center(35))
print('*    \\__|__/     *'.center(35))
print('*                *'.center(35))
print('*              *'.center(35))
print('*mmmmmmmmmmmm*'.center(35))
print(',*            *,'.center(35))
print(',*              *,*,'.center(37))
print(',*              *,  *, '.center(42))
print(',*    *,     ,*    *,  **,'.center(39))
print(',      ,     ,      ,   **,***'.center(43))
print(',      ,     ,     ,    **,*  *'.center(46))
print(',      ,     ,    ,  .. **,*  *'.center(46))
print(',     ,     ,    ,  . **,*  *'.center(46))
print(',    ,     ,    ,   ,*,****'.center(46))
print(", , ,  ,''''',  , , , *,".center(37))
print('( ( (___:     :___) ) )'.center(36))
=======
"""
    BroFar's Happy Bunny Rabbit Pattern Challenge.
    Created on February 21, 2023.
    Made by T0N1.
"""
print()
print()
print()
print('*           *'.center(35))
print('**           **'.center(35))
print('* *          * *'.center(35))
print('*  *        * *'.center(35))
print('*  *      *  *'.center(35))
print('*  *     *  *'.center(35))
print('*  *    *  *'.center(35))
print('* * ** * *'.center(35))
print('**    **'.center(35))
print('*          *'.center(35))
print('*   o   o   *'.center(35))
print('*     _      *'.center(35))
print('*  \\\\. V .//  *'.center(35))
print(',* ._       _.  *,'.center(35))
print('*    \\__|__/     *'.center(35))
print('*                *'.center(35))
print('*              *'.center(35))
print('*mmmmmmmmmmmm*'.center(35))
print(',*            *,'.center(35))
print(',*              *,*,'.center(37))
print(',*              *,  *, '.center(42))
print(',*    *,     ,*    *,  **,'.center(39))
print(',      ,     ,      ,   **,***'.center(43))
print(',      ,     ,     ,    **,*  *'.center(46))
print(',      ,     ,    ,  .. **,*  *'.center(46))
print(',     ,     ,    ,  . **,*  *'.center(46))
print(',    ,     ,    ,   ,*,****'.center(46))
print(", , ,  ,''''',  , , , *,".center(37))
print('( ( (___:     :___) ) )'.center(36))
>>>>>>> origin/main
